### ISSUE TITLE
Errors are getting lost in the shuffle

### ISSUE THREAD

**Issue by volkanunsal** [rackt/redux#538] opened 2015-08-16 01:45 UTC
The error messages from a specific function in my app are getting swallowed up somewhere in React or Redux. I haven't pinned down exactly where this is happening, but my hunch tells me that [this try/finally block](https://github.com/rackt/redux/blob/master/src%2FcreateStore.js#L101-L106) may be the root cause.

```javascript
    try {
      isDispatching = true;
      currentState = currentReducer(currentState, action);
    } finally {
      isDispatching = false;
    }
```

The error behavior is very peculiar and it is hard to describe, let alone reproduce. The first time the function is called, the errors work fine. However, if the function is called a second time, for example from a `componentDidUpdate` block, the error are not thrown at all. I had to wrap the body of the  function just to make sure there was error being thrown inside it.

This bug is hard to replicate, and I hope I managed to communicate the gist of it. I will keep investigating tomorrow.

**Comment by gaearon** [comment] 2015-08-16 05:30
Please keep investigating! Redux never catches exceptions. Try/finally block does not catch anything.

**Comment by gaearon** [comment] 2015-08-16 05:31
Don't forget you can check "Break on All Exceptions" in Chrome DevTools to see if your error is swallowed by some code.

**Comment by gaearon** [comment] 2015-08-16 06:24
I'm closing because we have no catch-es in the codebase, please reopen if you can reproduce.  

Do you use Redux DevTools? It catches reducer exceptions (and shows them), but it still logs them to console.

**Closed by gaearon** 2015-08-16 06:24 UTC

**Comment by tpreusse** [comment] 2015-08-17 13:25
I had a similar problem but the cause was not redux.

However running `dispatch` within the `then` callback of a promise is dangerous. Specifically because exceptions in a `then` callback of a already resolved promise are [ignored](https://promisesaplus.com/#point-61). Now since redux runs synchronously that means any render exception will be ignored when the render happens because of a dispatch in a then block of a already resolved promise.

To demonstrate I've adapted @gaearon Redux MircoBoilerplate:
https://gist.github.com/tpreusse/3d007762ed1026aefe47#file-reduxmicroboilerplate-js-L54

Unfortunately there is at least [one ajax library](https://github.com/mzabriskie/axios/blob/1629a026da17a1e1d8999a02f3fe6b6b60aaac9c/lib/axios.js#L32) that does return a resolved promise. So if you take the [original gist](https://gist.github.com/gaearon/074b0905337a6a835d82) and simply do `import { get as fetch } from 'axios';` you have exactly this issue. And thats why I'm here after 2 hours of debugging ;-(

Maybe this is something to mention in the docs? Or always include a catch block in the docs? I do feel like rendering from within a `then` block is a anti pattern but `dispatch` being synchronous is the greatest thing ever...

**Comment by volkanunsal** [comment] 2015-08-17 13:43
> because exceptions in a then callback of a already resolved promise are ignored. Now since redux runs synchronously that means any render exception will be ignored when the render happens because of a dispatch in a then block of a already resolved promise.

This is what happened with me, too. On the [fetch](https://github.com/github/fetch) issues page, I got [a pretty thorough answer](https://github.com/github/fetch/issues/194#issuecomment-131660428) with the suggestion of adding adding the error callback as the second argument to a `then` clause in order to prevent this type of error. I haven't tried it yet, but I will report back how it goes.

**Comment by tpreusse** [comment] 2015-08-17 14:17
At least GH `fetch` seems to be doing it right and does not return a resolved promise – did you attach a catch handler yourself which did not rethrow the exception?

I opened a issue at axios to get it resolved there:
https://github.com/mzabriskie/axios/issues/103

Would still be nice to add a warning to the redux async docs to be careful with then handlers.

**Comment by volkanunsal** [comment] 2015-08-17 14:35
> did you attach a catch handler yourself which did not rethrow the exception?

Yeah, I attached a `catch` at the end of the chain, but I had no idea about this global catch-all behavior. The documentation doesn't explain it clearly.

**Comment by gaearon** [comment] 2015-08-17 15:02
>Yeah, I attached a catch at the end of the chain, but I had no idea about this global catch-all behavior. >The documentation doesn't explain it clearly.

Which documentation are you referring to? Redux docs assume you know about Promise error catching behavior and its pitfalls.

**Comment by volkanunsal** [comment] 2015-08-17 16:32
@gaearon Whoops, I meant the `fetch` docs.
