### ISSUE TITLE
Issue with isPlainObject and many global contexts.

### ISSUE THREAD

**Issue by ALF-er** [rackt/redux#830] opened 2015-10-01 18:48 UTC
Hello, 

I'm writing one application which uses Electron and Redux.
In Electron there is Main Process and many Renderer Processes. I've created single Store in Main Process and want to use it across whole application. But, when I dispatch action (which is plain object) from Renderer process I get `Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.`
I found out that it happens cuz of this check https://github.com/rackt/redux/blob/master/src/utils/isPlainObject.js#L21
`instanceof` return false if constructors from different globals (in my case one from Main Process, another one from Renderer Process) [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) 

Maybe we can use different realization of isPlainObject? For example like [this](https://github.com/jquery/jquery/blob/master/src/core.js#L220) :smirk:

**Comment by qur2** [comment] 2015-10-01 19:14
You should write a custom one for you case. Check `redux-thunk` as an example: https://github.com/gaearon/redux-thunk/blob/master/src/index.js

Hope this helps!

**Comment by gaearon** [comment] 2015-10-01 19:34
Interesting. We took `isPlainObject` straight from Lodash? Does Lodash also have this problem?

**Comment by ALF-er** [comment] 2015-10-01 19:59
@qur2 yes, I can... But it'll be "workaround", not "fix". My action is plain object, but isPlainObject still wouldn't think so =)

@gaearon yeap, just tested https://www.npmjs.com/package/lodash.isplainobject and it also think that my `{ type: 'titler/mainWindow/INITIALIZED' }` not plain =|

**Comment by gaearon** [comment] 2015-10-01 20:10
@jdalton Maybe you can shed some light on what the behavior should be? I assume you know everything about this stuff.. :-)

**Comment by jdalton** [comment] 2015-10-01 20:28
I can't repro
```js
var is = require('lodash.isplainobject');
is({ type: 'titler/mainWindow/INITIALIZED' });
// => true
```

**Comment by jdalton** [comment] 2015-10-01 20:33
The description for a plain object is
> Checks if `value` is a plain object, that is, an object created by the `Object` constructor or one with a `[[Prototype]]` of `null`.

**Comment by travisperson** [comment] 2015-10-01 20:36
@jdalton It appears the issue is when `{ type: 'titler/mainWindow/INITIALIZED' }` is passed from one execution to another such as through the [Electron IPC(https://github.com/atom/electron/blob/master/docs/api/ipc-main-process.md).

**Comment by ALF-er** [comment] 2015-10-01 20:36
@jdalton issue reproduced when object created in one global context and checked with isPlainObject in different. See in "instanceof and multiple context (e.g. frames or windows)" on [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof)

**Comment by jdalton** [comment] 2015-10-01 20:42
I've fixed this issue on [master branch](https://github.com/lodash/lodash/blob/d407d8aa08a6f739441a82e3b7c9d8a5cf66ba16/lodash.js#L9008-L9022).

**Comment by jdalton** [comment] 2015-10-01 20:43
Also note worthy the object constructor is instanceof itself so if your object fails that then it's not created by the object constructor.

```js
Object instanceof Object
// => true
```

**Comment by ALF-er** [comment] 2015-10-01 20:51
Yes, but only if left operand was created in the same global context as the right operand

**Comment by jdalton** [comment] 2015-10-01 20:52
> Yes, but only if left operand was created in the same global context as the right operand

They are. It's like `object.constructor instanceof object.constructor`

**Comment by ALF-er** [comment] 2015-10-01 20:53
nope =) it's like `global1.object.constructor instanceof global2.object.constructor`

**Comment by jdalton** [comment] 2015-10-01 20:55
For lodash that's not the case:
```js
var Ctor = proto.constructor;
// then
Ctor instanceof Ctor
```
for redux it's
```
var constructor = proto.constructor;
// then
constructor instanceof constructor
```

So please point out where one is `global1` vs `global2`.

**Comment by ALF-er** [comment] 2015-10-01 20:57
alright, I'll try to create minimal demo to reproduce. Thanks anyway

**Comment by ALF-er** [comment] 2015-10-02 15:24
Sorry for delay. Here it is https://github.com/ALF-er/different-contexts-isPlainObject-test/ just npm install, npm start. 

It'will start electron-prebuilt with Main Process target script mainprocess.js. There is defined global.store with single method `dispatch` which use use lodash.isPlainObject to determine is parameter `action` plain. Also it will "dispatch" plain-object-action with type `ACTION_FROM_THE_SAME_GLOBAL_CONTEXT` which will be recognized as plain (Look at Terminal, Powershell, console etc. for output):
```
{ type: 'ACTION_FROM_THE_SAME_GLOBAL_CONTEXT' } true
```
Then it will spawn one window with rendererprocess.html and rendererprocess.js. It'll get `store` from main process via `remote.getGlobal("store")` ([doc](http://electron.atom.io/docs/v0.33.0/api/remote/#remote-getglobal-name)) and call it `dispatch` function with plain-object-action `{ type: "ACTION_FROM_ANOTHER_GLOBAL_CONTEXT" }` but in console we will see 
```
{ type: 'ACTION_FROM_ANOTHER_GLOBAL_CONTEXT' } false
```

I hope, this example will help

PS: Sorry for my English =|

**Comment by jdalton** [comment] 2015-10-02 15:43
Thanks for the repro. It looks like a bug with however Electron is handling it as the `action` constructor is clearly an `instanceof` itself (as an Object constructor is) but it's not reporting that.
```js
action.__proto__.a = 1;
action.constructor.a // 1
```

**Comment by jdalton** [comment] 2015-10-02 15:44
It's a pretty basic language level thing so I don't see it as something that needs to be addressed by `isPlainObject`. If you want to ensure it's a plain object convert it to one with an `Object.assign` equiv.

**Comment by ALF-er** [comment] 2015-10-02 15:47
Do you think it worth to public this issue in Electron repo? =|

**Comment by jdalton** [comment] 2015-10-02 15:51
Yep.

**Comment by gaearon** [comment] 2015-10-03 16:17
The issue at Electron was closed as wontfix.
What is our course of action here?

**Comment by jdalton** [comment] 2015-10-03 17:10
From the [electron issue](https://github.com/atom/electron/issues/2966):
> The object returned by remote module is not the original object, it is a proxy object that routes the calls to methods and properties to the main process and sends the result back, so operations that rely on object equivalence like instanceof won't work for it.

A proxy object doesn't sound like a plain object. So I'd say the `isPlainObject` method is doing its job. Lodash has a `toPlainObject` method so maybe something like that would be applicable for redux too.

**Comment by ALF-er** [comment] 2015-10-03 17:17
I'm totally agree that it's not lodash.isPlainObject or redux.isPlainObject issue... For me it's strange that Electron team `wontfix` it =| I think it's clearly "magic" behavior that fixable in electron 

I will just workaround it via middleware.

Thanks for all

**Closed** 2015-10-03 18:00 UTC
Labels: bug
