### ISSUE TITLE
Be less opinionated in combineReducers

### ISSUE THREAD

**Issue by ashaffer** [rackt/redux#715] opened 2015-09-13 02:01 UTC
I know I can just make my own, and I will do that for now, but it seems like combineReducers should not be quite so opinionated about the state shape.  For instance, in my app, I want to do something like this:

```javascript
reduceReducers(
  handleActions(someGlobalActions),
  combineReducers({
    entities,
    collections: combineReducers({
      explore,
      following
    })
  })
})
```

But this does not work in a very non-obvious way.  It doesn't work because combineReducers will drop any keys that are not in the state shape passed to it, so all of the things done in my global actions will not be recorded.

**Comment by gaearon** [comment] 2015-09-13 04:01
If we allow (and pass through) arbitrary keys, we wouldn't be able to guard against a very common beginner mistake when the shape of the initial state doesn't match the reducer shape. Utilities that ship with Redux just illustrate patterns and provide guidance to beginners. It's indeed often better to write your own when you know what you need. In this case, I believe your pattern of usage deviates from the simple case `combineReducers()` was designed for.

Still, I agree silently omitting keys isn't nice. We should at least warn this is happening. There is code for this, but it only executes once—perhaps we should always run it? (In development only, of course.)

**Comment by gaearon** [comment] 2015-09-13 04:02
cc @ellbee

**Comment by ellbee** [comment] 2015-09-13 16:29
I agree that silently omitting the keys isn't nice. The state shape check is only executed once because it felt unnecessary to be calling it every time. I don't think calling it every time would have any bad side effects and it would warn for cases like this.

**Comment by gaearon** [comment] 2015-09-13 16:44
I'm happy to accept a pull request amending this, given that the warning wording makes sense in both situations.

**Comment by gaearon** [comment] 2015-09-14 20:58
Fixed by https://github.com/rackt/redux/pull/720, will be released in the next minor release.

**Closed by gaearon** 2015-09-14 20:58 UTC
Labels: discussion

**Comment by gaearon** [comment] 2015-09-25 22:28
The new warning is out in 3.0.1.
Please verify!
