### ISSUE TITLE
I found it's complex to handle this type of data in reducer.

### ISSUE THREAD

**Issue by WenXuanYuan** [rackt/redux#1046] opened 2015-11-17 11:58 UTC
I wrote a Tree component with Redux to handle my state , the structure of the state used like this:
let cate = {
  '1': {
    expand: true,
    children: {
      '1_1': {
        expand: false,
        children: {
          '1_1_1': {
            expand: false
          },
          '1_1_2': {
            expand: false
          }
        }
      }
    }
  }
}
When I want to change cate['1']['children']['1_1']['expand'] equal true in reducer , I found it's very difficult with code like 
return {
  ...state,
  //Here I don`t know how to do.
} 
I am a fresher in Redux, could you give me a solution? thank you!

**Comment by just-boris** [comment] 2015-11-17 13:01
Try https://github.com/facebook/immutable-js. This library does all this work for you.

```
let cate = Immutable.fromJS({/*your tree will be here*/});
cate.setIn(["1", "children", "1_1", "expand"], true);
```

**Comment by simplesmiler** [comment] 2015-11-17 13:25
Another option is https://github.com/baptistemanson/immutable-path.

**Comment by gaearon** [comment] 2015-11-17 15:24
This is a duplicate of https://github.com/rackt/redux/issues/994. Use reducer composition pattern. Reducers can call other reducers to handle parts of their state. Also, `shopping-cart` example in the repo shows how to do it.

**Closed by gaearon** 2015-11-17 15:24 UTC
Labels: question
