### ISSUE TITLE
Bug in redux docs basic example 

### ISSUE THREAD

**Issue by Thunderbolt-sx** [rackt/redux#1040] opened 2015-11-16 01:55 UTC
I have just finished reading redux document basics part. There is potentially a bug in [basic secion](https://github.com/rackt/redux/issues/new). 

If you add three todos, and switch to active filter, click first (which will disappear from list), and you are not able to 'complete' the first todo in those two left. 

I think the problem is that in this example code, App only receive todos from 'current selected', and the 'map' function will generate index form this subset of state.todos(the singleton). However, 'COMPLETE_TODO' update index counting in that singleton todos. And there is no way those index matches (other than the case 'SHOW_ALL', as those two lists are equal).

**Comment by gaearon** [comment] 2015-11-16 13:32
This is a duplicate of https://github.com/rackt/redux/pull/795.
Let's discuss there.
We'll fix it eventually.

**Closed by gaearon** 2015-11-16 13:32 UTC
