### ISSUE TITLE
v3.0.3 seems to be a breaking change

### ISSUE THREAD

**Issue by neverfox** [rackt/redux#977] opened 2015-10-29 18:30 UTC
I wasn't getting a re-render on one of my components after doing an `npm update`. I finally reverted everything and tracked it down to the move from redux 3.0.2 to 3.0.3. Given semantic versioning, I assume it wasn't expected that this would break anything, so what might be going on here? What should I be looking for?

**Comment by gaearon** [comment] 2015-10-29 18:38
Duplicate of https://github.com/rackt/redux/issues/935. You were mutating state in the reducers, and that your code worked before was a coincidence. We can't enforce purity in JavaScript, so our best shot is to warn on every doc page that reducers must be pure, and cannot modify the state or the action. Indeed, 3.0.3 could break the apps that relied on the broken behavior, but it was never the support behavior in the first place, and you'd notice it was broken if you subscribed to a more specific state slice. This is why I don't consider this to be a breaking change.

**Closed by gaearon** 2015-10-29 18:38 UTC

**Comment by gaearon** [comment] 2015-10-29 18:43
To clarify: the pattern you used was just as broken before 3.0.3.
It's not like 3.0.3 added some new restrictions that would qualify for a breaking change.

You would see it *is* a bug if you subscribed one level deeper than you did in the view.
Then it wouldn't update either—whether in 3.0.3, 3.0.2, or earlier.

The implementation details changed in 3.0.3, and it so happens that the bug in your app surfaced.
However the docs explicitly warn that mutating the state is an unsupported way of using Redux.

**Comment by neverfox** [comment] 2015-10-29 19:36
> You were mutating state in the reducers, and that your code worked before was a coincidence.

Yep. Just discovered that and came back to report and close. Thanks for confirming that as the problem. Sorry for the duplicate and any frustration it caused.

> Indeed, 3.0.3 could break the apps that relied on the broken behavior, but it was never the supported behavior in the first place, and you'd notice it was broken if you subscribed to a more specific state slice. This is why I don't consider this to be a breaking change.

No need to justify it. That's perfectly reasonable and I went into the issue assuming the problem was on my end. I even said to my team that this is probably a case where we were getting by on the side-effect of some problem that 3.0.3 fixed. I just wasn't up to speed on where to start looking. I understand that reducers should be pure in redux; the mutation was unintentional. Now to wade through some ImmutableJS code and figure out why.

**Comment by gaearon** [comment] 2015-10-29 19:42
If you know which part of the app stopped updating, take a look at the state slice it was subscribed to. This state slice is apparently managed by `combineReducers()` in your app. In 3.0.2, `combineReducers()` changed the state identity any time an action fires, regardless of whether anything inside actually changed. In 3.0.3, it keeps the old reference if all the reducers returned referentially equal state values. This means the mistake can be in two places:

* Maybe the subscriptions code (e.g. `connect()` call from React Redux) is actually reading an unchanged slice of state, and now that `combineReducers()` is optimized, it no longer updates on every action. The fix is to subscribe to the part of the state that changes, and that the component renders.

* Maybe one of the reducers under `combineReducers()` mutates the `state` argument in some cases instead of returning the new state. Then, if the components are subscribed to the `combineReducers()` result, they won't see be redrawn on changes.

**Comment by neverfox** [comment] 2015-10-29 21:18
It was the latter. We have a reducer we were combining with the one returned from `combineReducers` using `reduceReducers` that was managing cross-domain actions. Since we had access to the whole state object, we failed to use the `...state` approach with overrides and had set the value of one of the domain properties directly.

**Comment by neverfox** [comment] 2015-10-29 21:20
Thanks for your advice.
