### ISSUE TITLE
State changes are not propogated to the components when there is a change in an object which is a part of the store state.

### ISSUE THREAD

**Issue by olwen1987** [rackt/redux#614] opened 2015-08-24 18:56 UTC
Consider i have an object in the main state x = {a:2}.
On some action i add another key value pair to the object x in state so the new object in the store state is x={a:2,b:3}. But this particular change is state is not propogated to the components and the component is not re-rendered.

I feel the issue is because the Type x in store state is still "Object" and we dont actually compare the actual value. 

Please let me know if you need more explanation on this.

**Comment by gaearon** [comment] 2015-08-24 18:57
How do you “add another key value pair” in code?

**Comment by gaearon** [comment] 2015-08-24 18:57
See also: http://rackt.github.io/redux/docs/Troubleshooting.html

**Comment by gaearon** [comment] 2015-08-24 19:05
I'm closing as most likely you're seeing the problem because you might be mutating the state.
Please reopen if you're sure you're not mutating it, and you put up a repo to reproduce the issue.

**Closed by gaearon** 2015-08-24 19:05 UTC
Labels: question

**Comment by gaearon** [comment] 2015-08-24 19:10
See also:

* [no trigger re-render with ajax](https://github.com/rackt/redux/issues/342)
* [Connector only checks state in shouldComponentUpdate](https://github.com/rackt/react-redux/issues/45)
* [Connector should use deepEqual](https://github.com/rackt/react-redux/issues/12)
* [Component won't re-render (universal)](https://github.com/rackt/redux/issues/610)
* [Components not re-rendering with connect](https://github.com/rackt/redux/issues/585)

**Comment by olwen1987** [comment] 2015-08-24 19:11
My Action:
var a= {};
export function change(key, value) {
    a[key] = value;
    return {type: SEARCH_CRITERIA, a};
}
My Reducer:

export const a = createReducer([], {
    [SEARCH_CRITERIA](state, action)  {
        return action.a;
    }
});

**Comment by olwen1987** [comment] 2015-08-24 19:12
Thanks for the help though. You have been pretty quick on response.

**Comment by gaearon** [comment] 2015-08-24 19:17
This is the problem I described above and [linked to](http://rackt.github.io/redux/docs/Troubleshooting.html).

You might need to go through the [basics tutorial](http://rackt.github.io/redux/docs/basics/index.html) because that's not how Redux works. You shouldn't keep an object like `a` outside. **The state should be managed exclusively by reducer.**

Here's the correct way to write the same code:

#### `actions.js`
```js
export function change(key, value) {
  return {type: SEARCH_CRITERIA, key, value};
}
```

#### `reducers.js`

```js
// Not sure what you wanted to do here
// You can use createReducer or similar helper, but I'll just write a function to be clear
export function search(state = {}, action) {
  switch (action.type) {
  case SEARCH_CRITERIA:
    // Do something with that object I guess?
    // For example, extend with a new key-value pair:
    return Object.assign({}, state, { [action.key]: action.value });
  default:
    return state;
}
```

**Comment by olwen1987** [comment] 2015-08-24 19:18
Cool thanks for the help. 
Will do the changes.

**Comment by olwen1987** [comment] 2015-08-24 19:26
Thanks that solution worked. 
Good Work :+1:
