### ISSUE TITLE
React Hot Reloading not working in real-world example

### ISSUE THREAD

**Issue by KeKs0r** [rackt/redux#832] opened 2015-10-02 10:31 UTC
I just started to play around with the examples (Counter & Real World) and I realized that the hot-reloading for the real world example is not working. 

Not sure where the differences between those examples are from a webpack perspective.

**Comment by gaearon** [comment] 2015-10-02 13:08
Please share the exact steps that don't work. This will help diagnose the issue.

**Comment by KeKs0r** [comment] 2015-10-02 13:28
I just followed the regular instruction for the example and then adding just a text e.g. in this line:
https://github.com/rackt/redux/blob/master/examples/real-world/components/Explore.js#L48

**Comment by gaearon** [comment] 2015-10-02 13:31
I can't reproduce this.

**Comment by KeKs0r** [comment] 2015-10-02 13:32
Ill fetch redux newly from master and retry from scratch.

**Comment by KeKs0r** [comment] 2015-10-02 13:39
You were right. I did some other change that breaks the hot reloading:
I added `react-transform-catch-errors`
```
{
  "stage": 2,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }
      }
    }
  }
}
```

**Comment by travisperson** [comment] 2015-10-02 13:44
I've noticed that depending on how quickly I save changes, sometimes things
don't get picked up as actually having changed and I am forced to save the
file again (just save, not make any changes) before webpack catches it and
does the correct thing. I don't believe this is actually a webpack issue,
I'm pretty sure this might be an issue with the file systems notify, but
not certain.

**Comment by KeKs0r** [comment] 2015-10-02 13:47
For me it actually picks up the changes, but I get:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
process-update.js:60 
[HMR]  - ./components/Lineup.js process-update.js:91 
[HMR] Reloading page
```

**Comment by gaearon** [comment] 2015-10-02 15:35
@travisperson 

Whether Webpack's or lower level issue, it's not something we can help you with here—please report upstream.

@KeKs0r 

>You were right. I did some other change that breaks the hot reloading:
>I added react-transform-catch-errors

I added it to `real-world` example and still can't reproduce the problem.

>[HMR] The following modules couldn't be hot updated: 

Please share the reproducible example on Github and then I can help you.
This is not an issue with `real-world` example so I'm closing.

**Closed by gaearon** 2015-10-02 15:35 UTC
Labels: examples

**Comment by travisperson** [comment] 2015-10-02 16:14
@gaearon yes, I know, just giving input to the problem stated above saying that it's not webpack, hence not an issue with the repo. Just trying to help resolve the issue.

**Comment by vincentfretin** [comment] 2015-10-03 10:44
@travisperson I had issue with vim editor which didn't notify changes to webpack watcher, the comment there gave me the answer: https://github.com/webpack/webpack/issues/781#issuecomment-95523711

**Comment by KeKs0r** [comment] 2015-10-03 11:10
@gaearon: To be honest I could not reproduce it with a minimal set of changes. I refetched the repository from my own fork and made the same changes. Then it worked. 
I also managed to screw up the counter example. Then pushed those changes to my fork. Clone it in another location and there it seems to work. So it might be a very weird edgecase or something else. I can't really tell what is different between my local 2 repositories. Only thing I know is that the code is the same.

**Comment by gaearon** [comment] 2015-10-03 14:55
Try killing `node_modules` and re-running `npm install`. Maybe something bad got cached.

**Comment by rodrigoruiz** [comment] 2015-12-16 07:09
Did you find a solution?
I'm running into the same problem.
For me, if I restart the server, it works again, but when I actually click on a react router link and then make changes in the code, it gives me the error message:
[HMR] Update check failed: parse@[native code]
onreadystatechange@http://localhost:3000/bundle.js:44:38

**Comment by KeKs0r** [comment] 2015-12-16 13:31
I have realized that it is something in the environment and not on the code itself. On my current machine hot loading seems to have an issue in general. But I did not have the time to really dig deeper into it. Although the same code (especially hot loading) just works fine on other machines.

**Comment by aaeronn** [comment] 2016-01-22 10:04
I downloaded the real world example and ran it.. it works fine.. but when I do any changes on the code it is not reflected in the browser.. it is strongly cached ?? What should I do ??

**Comment by ngalluzzo** [comment] 2016-03-16 23:07
Make sure you are using the babel preset for hmr

https://github.com/danmartinez101/babel-preset-react-hmre
