### ISSUE TITLE
todos-with-undo example use of distinctState doesn't work wrt to Completed todos

### ISSUE THREAD

**Issue by deep108** [rackt/redux#1045] opened 2015-11-17 02:41 UTC
If I've understood correctly, using react-undo with the distinctState() filter means that if the action didn't result in a state change, it shouldn't change the undo state.

When I click on an already completed todo, the current example treats it like a mutating action and I have to hit 'Redo' for each time I clicked on the already completed todo, even though nothing 'really' changed.

Assuming this isn't the intended behavior it seems one could either put a check in the 'COMPLETE_UNDO' reducer to see if the todo is already completed, or make a custom filter that's smarter than distinctState().

I'm just starting with redux et. al so I'm not sure what the preferred solution might be.

**Comment by omnidan** [comment] 2015-11-17 11:48
Feel free to correct me if I misunderstood - Marking todo items as done should be added to the history, as it's an action the user takes, thus it should be undoable. If you want to prevent this, you can use the [`excludeAction` helper](https://github.com/omnidan/redux-undo#filtering-actions).

**Comment by just-boris** [comment] 2015-11-17 11:57
As far as I understand, there is an issue when you have several `COMPLETE_TODO` actions in a row. You can't just exclude them all, only further actions without actual effect. How it can be done?

**Comment by omnidan** [comment] 2015-11-17 13:12
@just-boris I'm confused. If you exclude `COMPLETE_TODO` actions none of them should be added to the history. If you don't they will show up in the history, of course. And that's intended behavior in the example.

**Comment by just-boris** [comment] 2015-11-17 13:37
@omnidan okay, but can I dymamically exclude action based not only type but and current (beforeAction) state too. Something like this logic:

```
function filterActions(action, state) {
  // we are interested only in COMPLETE_TODO with uncompleted todos 
  return action.type !== COMPLETE_TODO || !state.done; 
}
```

Is there a way to get state to this filter?

**Comment by omnidan** [comment] 2015-11-17 13:43
@just-boris Yes, in your filter function you can do anything you want.

The signature of the function is `function filterState(action, currentState, previousState) {`. The distinct state helper looks like this:

```js
(action, currentState, previousState) => currentState !== previousState
```

Does this help you? :grin:

**Comment by just-boris** [comment] 2015-11-17 14:23
Oh, sorry, I missed this section, while reading readme. Of course it helps, thank you!

**Comment by omnidan** [comment] 2015-11-17 16:15
You're welcome :smile:

**Comment by deep108** [comment] 2015-11-17 23:00
The question I have (which I should have clarified) is should the 'todos-with-undo' example be updated? It uses the distinctState() filter, implying that it will deal with a COMPLETE_TODO action on an already completed todo, but it doesn't work that way. 

If it should be updated, would it be better to handle this in the reducer:
```
case COMPLETE_TODO:
  if (state[action.index].completed === true) {
    return state
  }
  ... [existing sample code]
```

or would it be better to do it in a redux-undo filter as described above?

**Comment by omnidan** [comment] 2015-11-17 23:04
@deep108 I'm not sure I understand the issue. With the `distinctState()` filter, if the state is changed in any way, it *will* be stored in the history - that's intended behavior.

If you want to filter out additional actions, doing it in a redux-undo filter would probably be the best way to do it.

**Comment by deep108** [comment] 2015-11-17 23:44
@omnidan What I see is that the todos-with-undo example doesn't seem like the best possible example in this particular case. If the result of an action like completing an already completed undo is essentially a no-op, as an end-user I wouldn't expect it to update history (or at least that's what I experienced when playing with the app). Nothing happens onscreen to indicate state changed either when you complete a completed todo, or when you undo back to essentially the identical state.

Completing a completed undo does change the state, so distinctState will do what it's designed to do, but in practical terms the state didn't *really* change. From a UI perspective, it doesn't seem ideal, and I thought it might be a good thing to deal with in an example.

**Comment by omnidan** [comment] 2015-11-17 23:55
@deep108 Ah, I get you now. Completing an already completed todo item is not possible (UI-wise) in this example, but you might want to do something *like* that in *your* app. Sure, then putting it into the filterAction would be the best way to do it.

Another way to work around this would be making sure there's nothing in (or a part of) the state that isn't reflected in UI. That way when the state changes something in the UI always changes too. (and you don't have a no-op from the UI perspective)

The example already does this, though, and unfortunately it still doesn't work because of the way Arrays work in JS. The best way (IMO) to fix this, is using immutables, then `distinctState()` will work fine even when the state "changed", as `===` will always return `true` when the states are (data-wise) the same.

Does this help/make sense to you?

**Comment by deep108** [comment] 2015-11-18 01:13
@omnidan Yes, mostly. I wouldn't really want to do something like that in my own app. It's more that if I were writing a todo app, I wouldn't want completing a completed todo to change state, either as it relates to the UI or the undo history.

Immutables seem like a good solution (as they almost always are...).

Thanks.

**Comment by omnidan** [comment] 2015-11-18 01:38
@deep108 I understand where you're coming from, but completing a completed todo is not really possible unless you tweak the example or manually dispatch another complete action - so it wouldn't make sense to prevent it in the example.

If this is something you really need, using immutables or writing your own filter action will be your best bet. :smile:

I hope everything is clear now! :)

**Comment by deep108** [comment] 2015-11-18 08:42
> @deep108 I understand where you're coming from, but completing a completed todo is not really possible unless you tweak the example or manually dispatch another complete action - so it wouldn't make sense to prevent it in the example.

@omnidan Actually, that's the point I was trying to make. The todos-with-undo example **does** dispatch another complete action when you click on an already completed todo, and it has the side-effect of adding to the undo-history even though nothing *really* changed. I made things confusing by talking about the distinctState() filter.

The questions were should the example be updated, and if so what would be the best way to fix the problem?

**Comment by omnidan** [comment] 2015-11-18 09:56
@deep108 When you click on an already completed todo the example should mark it as uncompleted, which changes the state of the todo item to uncompleted. Is this not happening for you?

**Comment by mist123** [comment] 2015-11-18 10:07
@omnidan it's not happening for me too.
`todos` reducer always marks todo as completed: https://github.com/rackt/redux/blob/master/examples/todos-with-undo/reducers.js#L30

**Comment by gaearon** [comment] 2015-11-18 10:08
> even though nothing really changed. 

It should make it “uncompleted”. If it doesn't, you're probably seeing the bug described in #795. It affects both the tutorial and `todos-with-undo` example and should be fixed in both. Let's discuss it in #795.

**Comment by deep108** [comment] 2015-11-20 04:14
@omnidan @gaearon Sorry to keep beating this dead horse, but I don't think the problem is related to * #795. I'm able to reproduce the problem when showing 'All' todos or just 'Active'. As @mist123 points out the reducer for COMPLETE_TODO always sets 'completed' to true. There's no logic to un-complete a todo:
```
    case COMPLETE_TODO:
      return [
        ...state.slice(0, action.index),
        Object.assign({}, state[action.index], {
          completed: true
        }),
        ...state.slice(action.index + 1)
      ]
```
One way to fix this would be to change the reducer to toggle the state:
```
          completed: !state[action.index].completed
```

Another would be to put toggle logic in the Todo onClick prop and pass the new 'completed' state in the COMPLETE_TODO action. I made sample changes in this commit: 
* deep108/redux@ 0c1fa3e25988871c8fda2d65f440f9d934e85e82

First way is a little simpler, but the second has the advantage that you can tell what the new state will be by looking at the action. I suppose you could do it with an UNCOMPLETE_TODO action as well. Not sure if there's a canonical redux-y (redux-ist? redux-tionary?) way to do this.

Anyway, something like this would fix both the inability to un-complete todos, and any concerns about useless undo history accumulating when you click on already completed todos. I can put together a pull request if any of these make sense.

**Comment by gaearon** [comment] 2015-11-20 11:18
Let's keep it open for now then.
I'm releasing Egghead videos about Redux soon.
They feature this todos example (no undo though) and have different code, so I want our docs and examples eventually to use that instead.
I'll let you folks know when it's public.

**Closed** 2016-01-27 14:04 UTC
Labels: question
